services:
  db:
    image: postgres:15-alpine
    ports:
      - "54322:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - deforum-internal

  backend:
    build: 
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "5000:5000"
    stop_grace_period: 5s
    stop_signal: SIGTERM
    command: /app/apps/api/start.sh
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      NODE_ENV: ${NODE_ENV}
    env_file:
      - .env
    volumes:
      - ./apps/api/prisma/migrations:/app/apps/api/prisma/migrations
    develop:
      watch:
        - action: sync
          path: ./apps/api/src
          target: /app/apps/api/src
          ignore:
            - node_modules/
            - dist/
        - action: sync
          path: ./apps/shared
          target: /app/apps/shared
          ignore:
            - node_modules/
            - dist/
        - action: rebuild
          path: ./apps/api/package.json
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - deforum-internal

  frontend:
    build: 
      context: .
      dockerfile: apps/client/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      VITE_API_URL: http://backend:5000/api
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: ./apps/client/src
          target: /app/apps/client/src
          ignore:
            - node_modules/
            - dist/
        - action: sync
          path: ./apps/client/public
          target: /app/apps/client/public
          ignore:
            - node_modules/
            - dist/
        - action: sync
          path: ./apps/shared
          target: /app/apps/shared
          ignore:
            - node_modules/
            - dist/
        - action: rebuild
          path: ./apps/client/package.json
    networks:
      - deforum-internal

volumes:
  db-data:

networks:
  deforum-internal:
    driver: bridge 