/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LeftSidebarImport } from './routes/_left-sidebar'
import { Route as AppImport } from './routes/_app'
import { Route as AppIndexImport } from './routes/_app/index'
import { Route as AppPostsPostIdImport } from './routes/_app/posts/$postId'

// Create/Update Routes

const LeftSidebarRoute = LeftSidebarImport.update({
  id: '/_left-sidebar',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)

const AppPostsPostIdRoute = AppPostsPostIdImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => AppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_left-sidebar': {
      id: '/_left-sidebar'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LeftSidebarImport
      parentRoute: typeof rootRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/posts/$postId': {
      id: '/_app/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof AppPostsPostIdImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppPostsPostIdRoute: typeof AppPostsPostIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppPostsPostIdRoute: AppPostsPostIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LeftSidebarRoute
  '/': typeof AppIndexRoute
  '/posts/$postId': typeof AppPostsPostIdRoute
}

export interface FileRoutesByTo {
  '': typeof LeftSidebarRoute
  '/': typeof AppIndexRoute
  '/posts/$postId': typeof AppPostsPostIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppRouteWithChildren
  '/_left-sidebar': typeof LeftSidebarRoute
  '/_app/': typeof AppIndexRoute
  '/_app/posts/$postId': typeof AppPostsPostIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/' | '/posts/$postId'
  fileRoutesByTo: FileRoutesByTo
  to: '' | '/' | '/posts/$postId'
  id: '__root__' | '/_app' | '/_left-sidebar' | '/_app/' | '/_app/posts/$postId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LeftSidebarRoute: typeof LeftSidebarRoute
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LeftSidebarRoute: LeftSidebarRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app",
        "/_left-sidebar"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/",
        "/_app/posts/$postId"
      ]
    },
    "/_left-sidebar": {
      "filePath": "_left-sidebar.tsx"
    },
    "/_app/": {
      "filePath": "_app/index.tsx",
      "parent": "/_app"
    },
    "/_app/posts/$postId": {
      "filePath": "_app/posts/$postId.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
